// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Normaize.DataNormalization.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Normaize.DataNormalization.Infrastructure.Migrations
{
    [DbContext(typeof(DataNormalizationDbContext))]
    [Migration("20251026194646_analysis_Add")]
    partial class analysis_Add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data_normalization")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Aggregates.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ComparisonDataSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_dataset_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonDataSetId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_analyses_created_at");

                    b.HasIndex("DataSetId")
                        .HasDatabaseName("ix_analyses_dataset_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_analyses_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_analyses_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_analyses_type");

                    b.HasIndex("DataSetId", "Status")
                        .HasDatabaseName("ix_analyses_dataset_status");

                    b.HasIndex("Status", "Type")
                        .HasDatabaseName("ix_analyses_status_type");

                    b.ToTable("analyses", "data_normalization");
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Aggregates.NormalizationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_retries");

                    b.Property<string>("OperationParameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("operation_parameters");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_type");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("progress_message");

                    b.Property<int>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress_percentage");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_normalization_jobs_created_at");

                    b.HasIndex("DataSetId")
                        .HasDatabaseName("ix_normalization_jobs_dataset_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_normalization_jobs_status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_normalization_jobs_status_created_at");

                    b.ToTable("normalization_jobs", "data_normalization");
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Entities.DataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Unique identifier for the dataset");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("When the dataset was deleted");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("deleted_by")
                        .HasComment("Who deleted the dataset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description")
                        .HasComment("Optional description of the dataset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Whether this dataset has been soft deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at")
                        .HasComment("When the dataset was last modified");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("last_modified_by")
                        .HasComment("Who last modified the dataset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Human-readable name of the dataset");

                    b.Property<string>("PreviewData")
                        .HasColumnType("jsonb")
                        .HasColumnName("preview_data")
                        .HasComment("Sample data for preview purposes");

                    b.Property<string>("ProcessedData")
                        .HasColumnType("jsonb")
                        .HasColumnName("processed_data")
                        .HasComment("Processed data for small datasets");

                    b.Property<string>("ProcessingErrors")
                        .HasColumnType("text")
                        .HasColumnName("processing_errors")
                        .HasComment("Any errors encountered during processing");

                    b.Property<DateTime?>("RetentionExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_expiry_date")
                        .HasComment("When this dataset should be automatically deleted");

                    b.Property<string>("Schema")
                        .HasColumnType("jsonb")
                        .HasColumnName("schema")
                        .HasComment("JSON schema definition for the dataset");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasComment("When the dataset was uploaded");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id")
                        .HasComment("ID of the user who owns this dataset");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_datasets_uploaded_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_datasets_user_id");

                    b.HasIndex("IsDeleted", "UserId")
                        .HasDatabaseName("ix_datasets_is_deleted_user_id");

                    b.ToTable("datasets", "data_normalization");
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Entities.DataSetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Unique identifier for the row");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("When this row was created");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data")
                        .HasComment("JSON representation of the row data");

                    b.Property<Guid>("DataSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id")
                        .HasComment("Foreign key to the parent dataset");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index")
                        .HasComment("Zero-based index of this row within the dataset");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("When this row was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_dataset_rows_created_at");

                    b.HasIndex("DataSetId")
                        .HasDatabaseName("ix_dataset_rows_dataset_id");

                    b.HasIndex("DataSetId", "RowIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_dataset_rows_dataset_id_row_index");

                    b.ToTable("dataset_rows", "data_normalization");
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Entities.NormalizationAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("NormalizationJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("normalization_job_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_logs_action");

                    b.HasIndex("NormalizationJobId")
                        .HasDatabaseName("ix_audit_logs_job_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("NormalizationJobId", "Timestamp")
                        .HasDatabaseName("ix_audit_logs_job_timestamp");

                    b.ToTable("normalization_audit_logs", "data_normalization");
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Aggregates.Analysis", b =>
                {
                    b.HasOne("Normaize.DataNormalization.Domain.Entities.DataSet", "ComparisonDataSet")
                        .WithMany()
                        .HasForeignKey("ComparisonDataSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Normaize.DataNormalization.Domain.Entities.DataSet", "DataSet")
                        .WithMany()
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComparisonDataSet");

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Aggregates.NormalizationJob", b =>
                {
                    b.HasOne("Normaize.DataNormalization.Domain.Entities.DataSet", "DataSet")
                        .WithMany()
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Entities.DataSet", b =>
                {
                    b.OwnsOne("Normaize.DataNormalization.Domain.ValueObjects.DatasetStatistics", "Statistics", b1 =>
                        {
                            b1.Property<Guid>("DataSetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColumnCount")
                                .HasColumnType("integer")
                                .HasColumnName("stats_column_count");

                            b1.Property<bool>("IsProcessed")
                                .HasColumnType("boolean")
                                .HasColumnName("stats_is_processed");

                            b1.Property<DateTime?>("ProcessedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("stats_processed_at");

                            b1.Property<int>("RowCount")
                                .HasColumnType("integer")
                                .HasColumnName("stats_row_count");

                            b1.Property<bool>("UseSeparateTable")
                                .HasColumnType("boolean")
                                .HasColumnName("stats_use_separate_table");

                            b1.HasKey("DataSetId");

                            b1.ToTable("datasets", "data_normalization");

                            b1.WithOwner()
                                .HasForeignKey("DataSetId");
                        });

                    b.OwnsOne("Normaize.DataNormalization.Domain.ValueObjects.FileMetadata", "FileInfo", b1 =>
                        {
                            b1.Property<Guid>("DataSetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DataHash")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("data_hash");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("file_path");

                            b1.Property<long>("FileSize")
                                .HasColumnType("bigint")
                                .HasColumnName("file_size");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("file_type");

                            b1.Property<string>("StorageProvider")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("storage_provider");

                            b1.HasKey("DataSetId");

                            b1.ToTable("datasets", "data_normalization");

                            b1.WithOwner()
                                .HasForeignKey("DataSetId");
                        });

                    b.Navigation("FileInfo")
                        .IsRequired();

                    b.Navigation("Statistics")
                        .IsRequired();
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Entities.DataSetRow", b =>
                {
                    b.HasOne("Normaize.DataNormalization.Domain.Entities.DataSet", "DataSet")
                        .WithMany()
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Entities.NormalizationAuditLog", b =>
                {
                    b.HasOne("Normaize.DataNormalization.Domain.Aggregates.NormalizationJob", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("NormalizationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Normaize.DataNormalization.Domain.Aggregates.NormalizationJob", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
