name: Auto Tag Version After Merge

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get last commit message
      id: last_commit
      run: |
        message=$(git log -1 --pretty=%B)
        echo "commit_message=${message}" >> $GITHUB_OUTPUT

    - name: Get version from csproj
      id: version
      run: |
        version=$(grep -o '<Version>.*</Version>' Normaize.API/Normaize.API.csproj | sed 's/<Version>\(.*\)<\/Version>/\1/')
        if [ -z "$version" ]; then
          version="1.0.0"
        fi
        echo "version=${version}" >> $GITHUB_OUTPUT

    - name: Create and push tag for new version
      if: ${{ contains(steps.last_commit.outputs.commit_message, 'chore: bump version to') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag "v${{ steps.version.outputs.version }}"
        git push origin "v${{ steps.version.outputs.version }}"