name: Pull Request Check

on:
  workflow_run:
    workflows: ["SonarQube Analysis"]
    branches: [ main, develop ]
    types: [completed]

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  validate:
    runs-on: ubuntu-latest
    # Only run if SonarQube analysis succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Check for vulnerabilities
      run: dotnet list package --vulnerable 