name: Version Bump

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    branches: [main]
    types: [completed]

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Get current version
      id: current-version
      run: |
        # Extract current version from .csproj files
        VERSION=$(grep -o '<Version>.*</Version>' Normaize.API/Normaize.API.csproj | sed 's/<Version>\(.*\)<\/Version>/\1/' || echo "1.0.0")
        
        # If no version found, default to 1.0.0
        if [ -z "$VERSION" ] || [ "$VERSION" = "" ]; then
          VERSION="1.0.0"
        fi
        
        echo "Current version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Determine version bump type
      id: bump-type
      run: |
        # Analyze commit messages since last version bump
        # Look for keywords to determine bump type
        COMMIT_MESSAGES=$(git log --oneline --since="1 day ago" | head -10)
        echo "Recent commits:"
        echo "$COMMIT_MESSAGES"
        
        if echo "$COMMIT_MESSAGES" | grep -qi "breaking\|major\|!:"; then
          echo "bump-type=major" >> $GITHUB_OUTPUT
          echo "Major version bump detected"
        elif echo "$COMMIT_MESSAGES" | grep -qi "feat\|feature\|new"; then
          echo "bump-type=minor" >> $GITHUB_OUTPUT
          echo "Minor version bump detected"
        else
          echo "bump-type=patch" >> $GITHUB_OUTPUT
          echo "Patch version bump detected"
        fi

    - name: Calculate new version
      id: new-version
      run: |
        CURRENT_VERSION="${{ steps.current-version.outputs.version }}"
        BUMP_TYPE="${{ steps.bump-type.outputs.bump-type }}"
        
        echo "Current version: $CURRENT_VERSION"
        echo "Bump type: $BUMP_TYPE"
        
        # Parse current version with fallback
        if [[ "$CURRENT_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          PATCH="${BASH_REMATCH[3]}"
        else
          echo "Invalid version format, defaulting to 1.0.0"
          MAJOR=1
          MINOR=0
          PATCH=0
        fi
        
        echo "Parsed version: $MAJOR.$MINOR.$PATCH"
        
        # Calculate new version based on bump type
        case $BUMP_TYPE in
          "major")
            NEW_MAJOR=$((MAJOR + 1))
            NEW_MINOR=0
            NEW_PATCH=0
            ;;
          "minor")
            NEW_MAJOR=$MAJOR
            NEW_MINOR=$((MINOR + 1))
            NEW_PATCH=0
            ;;
          "patch")
            NEW_MAJOR=$MAJOR
            NEW_MINOR=$MINOR
            NEW_PATCH=$((PATCH + 1))
            ;;
          *)
            echo "Unknown bump type, defaulting to patch"
            NEW_MAJOR=$MAJOR
            NEW_MINOR=$MINOR
            NEW_PATCH=$((PATCH + 1))
            ;;
        esac
        
        NEW_VERSION="$NEW_MAJOR.$NEW_MINOR.$NEW_PATCH"
        echo "New version: $NEW_VERSION"
        echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Update version in project files
      run: |
        NEW_VERSION="${{ steps.new-version.outputs.new-version }}"
        
        # Update all .csproj files
        find . -name "*.csproj" -exec sed -i "s/<Version>.*<\/Version>/<Version>$NEW_VERSION<\/Version>/g" {} \;
        
        # Update AssemblyInfo.cs if it exists
        find . -name "AssemblyInfo.cs" -exec sed -i "s/AssemblyVersion(\".*\")/AssemblyVersion(\"$NEW_VERSION\")/g" {} \; 2>/dev/null || true
        
        echo "Updated version to $NEW_VERSION in all project files"

    - name: Check for changes
      id: check-changes
      run: |
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
          echo "has-changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected"
          echo "has-changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create version bump commit
      if: steps.check-changes.outputs.has-changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git commit -m "chore: bump version to ${{ steps.new-version.outputs.new-version }} [skip ci]"
        
        # Push the commit
        git push origin main

    - name: Skip commit - no changes
      if: steps.check-changes.outputs.has-changes == 'false'
      run: |
        echo "No version changes detected, skipping commit"
        echo "This might happen if the version was already bumped or no relevant changes were made"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.new-version.outputs.new-version }}
        release_name: Release v${{ steps.new-version.outputs.new-version }}
        body: |
          ## Version ${{ steps.new-version.outputs.new-version }}
          
          This is an automated release created after successful CI/CD pipeline completion.
          
          ### Changes
          - Automated version bump
          - All tests passed
          - CI/CD pipeline successful
          
          ### Version Bump Type
          **${{ steps.bump-type.outputs.bump-type }}** version increment
          
          Previous version: ${{ steps.current-version.outputs.version }}
          New version: ${{ steps.new-version.outputs.new-version }}
        draft: false
        prerelease: false 